# Generated by Django 4.1.13 on 2023-12-11 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('parent_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_num', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nationality', models.CharField(max_length=3)),
                ('speciality', models.ManyToManyField(blank=True, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)])),
                ('manfacture_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
                ('purchased_gen', models.IntegerField(default=0)),
                ('purchased_24', models.IntegerField(default=0)),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
                ('company_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.company')),
            ],
        ),
    ]
