# Generated by Django 4.1 on 2023-12-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_company_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='shop_catego_categor_cb48d9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['p_id', 'slug'], name='shop_produc_p_id_ef8b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='shop_produc_product_8ef27c_idx'),
        ),
    ]
