# Generated by Django 4.1 on 2023-12-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='shop_compan_company_38c11e_idx'),
        ),
    ]
