# Generated by Django 4.1 on 2023-12-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="p_image",
            field=models.ImageField(blank=True, max_length=255, upload_to="products/"),
        ),
    ]
