# Generated by Django 4.1 on 2023-12-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='products/%slug/'),
        ),
    ]
