# Generated by Django 4.1 on 2023-12-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_p_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_image',
        ),
    ]
