# Generated by Django 4.1 on 2024-01-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_coupon_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_processed",
            field=models.BooleanField(default=False),
        ),
    ]
